---
title: Vinay Chilukuri
timezone: UTC
collections:
  cases:
    title: Cases
    output: true
    permalink: "/:collection/:path"
  other:
    title: Other
    output: true
  posts:
    title: Posts
    output: true
  reccos:
    title: Reccos
    output: false
  uploads:
    title: Uploads
    output: true
description: 
baseurl: ''
url: ''
twitter_username: vinaychilukuri
linkedin_username: vinaychilukuri
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
- jekyll-feed
